[BASIC]
[BASIC:PARAMS]
[BASIC:NETWORK]
beginTraining=0
connectionLimit=0
contextTargetOffset=0,0,0,0
contextTargetSize=0,0,0,0
endTraining=3
hasContext=f
inputCount=1
layerCounts=1,1,1,2
layerFeedCounts=1,0,0,1
layerContextCount=0,0,0,0
layerIndex=0,1,2,3
output=0,1,1,0,1
outputCount=1
weightIndex=0,1,1,1
weights=-0.0006198871
biasActivation=0,1,1,1
[BASIC:ACTIVATION]
"org.encog.engine.network.activation.ActivationTANH"
"org.encog.engine.network.activation.ActivationTANH"
"org.encog.engine.network.activation.ActivationTANH"
"org.encog.engine.network.activation.ActivationLinear"
